import Foundation

struct GuideItem: Identifiable, Decodable {
    var id = UUID()
    let title: String
    let description: String
    let imageName: String
    let content: String
    
    enum CodingKeys: String, CodingKey {
        case title
        case description
        case imageName
        case content
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        title = try container.decode(String.self, forKey: .title)
        description = try container.decode(String.self, forKey: .description)
        imageName = try container.decode(String.self, forKey: .imageName)
        content = try container.decode(String.self, forKey: .content)
        id = UUID()
    }
}

struct GuideData: Decodable {
    let indoor: [GuideItem]
    let outdoor: [GuideItem]
}

let jsonData = """
{
  "indoor": [
    {
      "title": "Common Household Objects",
      "description": "Look for devices hidden in everyday items like clocks, smoke detectors, and power adapters.",
      "imageName": "house.fill",
      "content": "Hidden cameras can be cleverly disguised as everyday household objects that blend seamlessly into any environment. Common hiding spots include:\\n\\n• **Digital Clocks**: Often placed on nightstands or shelves, these can contain tiny cameras behind the display. Look for unusual lens reflections or holes that don't match the clock's design.\\n\\n• **Smoke Detectors**: Legitimate smoke detectors are usually mounted on ceilings, but fake ones may be positioned at eye level. Check for any that seem out of place or have unusual blinking patterns.\\n\\n• **Power Adapters and USB Chargers**: These devices can house cameras while appearing to be functional chargers. Be suspicious of chargers left plugged in unusual locations or those you didn't bring yourself.\\n\\n• **Air Fresheners**: Both plug-in and standalone air fresheners can conceal cameras. Pay attention to any that are positioned to face beds or private areas.\\n\\n• **Picture Frames**: Digital photo frames or even regular frames can hide cameras behind the glass. Look for any frames positioned unusually or facing private spaces.\\n\\n**Detection Tips**:\\n- Use your phone's flashlight to scan for lens reflections\\n- Check for items that seem oddly positioned or face private areas\\n- Look for small holes or gaps that could hide a camera lens\\n- Notice any objects with unnecessary wires or that feel unusually warm"
    },
    {
      "title": "Furniture and Decor",
      "description": "Check inside cushions, behind mirrors, and within decorative items.",
      "imageName": "sofa.fill",
      "content": "Furniture and decorative items provide excellent concealment opportunities for hidden cameras due to their ubiquitous presence and varied designs. Key areas to inspect include:\\n\\n• **Mirrors**: Two-way mirrors can hide cameras. Test by placing your fingernail against the glass - if there's a gap between your nail and its reflection, it's likely a regular mirror. No gap may indicate a two-way mirror.\\n\\n• **Decorative Items**: Vases, sculptures, and ornaments can house cameras. Be particularly wary of items positioned to oversee beds, bathrooms, or changing areas.\\n\\n• **Cushions and Pillows**: Cameras can be sewn into seams or hidden within stuffing. Feel for any hard objects or unusual bulges in soft furnishings.\\n\\n• **Books and Bookshelves**: Fake books or hollowed-out real books on shelves can conceal recording devices. Look for books that seem out of place or have unusual thickness.\\n\\n• **Wall Decorations**: Paintings, posters, and wall hangings can hide cameras behind them. Check for any that seem to bulge outward or have small holes.\\n\\n• **Lamps and Light Fixtures**: Table lamps and ceiling fixtures offer power sources and concealment. Inspect lampshades and bases for any modifications.\\n\\n**What to Look For**:\\n- Unusual holes or gaps in furniture\\n- Items that seem heavier than they should be\\n- Decorations positioned to face private areas\\n- Any furniture with unexpected wires or cables\\n- Objects that emit unexpected heat or sounds"
    },
    {
      "title": "Electronics",
      "description": "Examine TVs, gaming consoles, computers, and other electronic devices for added components.",
      "imageName": "tv.fill",
      "content": "Electronic devices are particularly favored for hiding cameras because they naturally have power sources, LEDs, and various openings that can camouflage recording equipment. Critical devices to examine include:\\n\\n• **Televisions and Monitors**: Modern smart TVs may have built-in cameras, but additional hidden cameras can be attached. Check around bezels, speakers grilles, and ventilation slots.\\n\\n• **Cable/Satellite Boxes**: These devices are often positioned with clear views of rooms. Inspect for any modifications, extra cables, or lens-like openings.\\n\\n• **Gaming Consoles**: Both the console and accessories (like motion sensors) can be modified. Look for any non-standard attachments or unusual positioning.\\n\\n• **Computers and Webcams**: Beyond obvious webcams, cameras can be hidden in keyboards, mice, or external drives. Cover built-in webcams when not in use.\\n\\n• **Speakers and Sound Systems**: Bluetooth speakers and soundbars can conceal cameras within speaker grilles. Check for any that are positioned unusually or have unexpected features.\\n\\n• **Routers and Modems**: Network equipment is rarely moved and often overlooked. Inspect for any modifications or attached devices.\\n\\n**Red Flags to Notice**:\\n- Electronics with new or unusual LED lights\\n- Devices that are warm when supposedly turned off\\n- Extra cables that don't seem necessary\\n- Equipment positioned to face private areas\\n- Any electronics you don't recognize or didn't place yourself\\n\\n**Protection Measures**:\\n- Unplug devices you don't need\\n- Cover cameras on laptops and smart TVs\\n- Use your own chargers and cables when traveling\\n- Be wary of any pre-installed electronics in rentals"
    },
    {
      "title": "Vents and Fixtures",
      "description": "Inspect air vents, light fixtures, and electrical outlets.",
      "imageName": "fan.desk",
      "content": "Built-in fixtures and ventilation systems offer ideal hiding spots for surveillance equipment because they're permanent installations that people rarely examine closely. Key areas requiring inspection include:\\n\\n• **Air Vents and Grilles**: HVAC vents provide concealment and often have slats that can hide camera lenses. Use a flashlight to peer inside and look for any devices that don't belong.\\n\\n• **Ceiling Light Fixtures**: Overhead lighting provides power and elevated viewing angles. Check for any fixtures that seem newer than others or have unusual modifications.\\n\\n• **Electrical Outlets**: Fake outlets or modified real ones can house cameras. Test all outlets and look for any that are positioned unusually high (at eye level rather than near the floor).\\n\\n• **Switch Plates**: Light switches and dimmer controls can be replaced with units containing cameras. Look for any that protrude more than others or have tiny holes.\\n\\n• **Ceiling Fans**: The motor housing and blades can conceal devices. Check for any additions or modifications to the fan assembly.\\n\\n• **Bathroom Fixtures**: Exhaust fans, heated towel rails, and even shower heads have been used to hide cameras. Pay special attention to any fixtures that face the shower or toilet.\\n\\n**Inspection Techniques**:\\n- Use a flashlight at an angle to reveal hidden lenses\\n- Check if fixtures are securely mounted or seem loose\\n- Look for any fixtures that appear newer or different from others\\n- Notice any unnecessary wires running to or from fixtures\\n- Test all electrical outlets to ensure they're functional\\n\\n**Warning Signs**:\\n- Fixtures positioned in unusual locations\\n- Vents that don't seem to connect to HVAC systems\\n- Light fixtures with extra wires or components\\n- Any fixture that seems to have been recently installed or modified"
    },
    {
      "title": "Toys and Stuffed Animals",
      "description": "Some devices can be hidden inside children's toys.",
      "imageName": "figure.stand",
      "content": "Children's toys and stuffed animals are particularly concerning hiding places for surveillance devices because they're designed to be in bedrooms and private spaces while appearing completely innocent. Areas of concern include:\\n\\n• **Stuffed Animals**: Teddy bears and plush toys can have cameras hidden in eyes or sewn into the body. Feel for any hard objects inside the stuffing or unusual weight distribution.\\n\\n• **Electronic Toys**: Any toy with batteries or power can potentially house a camera. Be especially cautious of toys with screens, speakers, or interactive features.\\n\\n• **Dolls and Action Figures**: Cameras can be placed in heads or torsos. Check for any modifications or holes that weren't part of the original design.\\n\\n• **Building Blocks and Models**: Larger LEGO structures or model sets can conceal devices within their construction. Look for any non-standard pieces or modifications.\\n\\n• **Board Games and Puzzles**: Game boxes on shelves can hide recording equipment. Check any games that seem to be positioned to observe the room rather than stored normally.\\n\\n• **Baby Monitors**: While legitimate monitors are important for child safety, additional hidden cameras may be disguised as toys near cribs or play areas.\\n\\n**Safety Checks**:\\n- Examine all toys in bedrooms and private areas\\n- Feel stuffed animals for hard objects or unusual weight\\n- Check toy eyes for lens reflections\\n- Look for toys positioned to view beds or changing areas\\n- Be cautious of any toys you didn't purchase yourself\\n\\n**Protection Tips**:\\n- Regularly inspect children's rooms\\n- Be wary of second-hand toys\\n- Store unfamiliar toys outside of private areas\\n- Educate older children about privacy concerns\\n- Consider using RF detectors designed to find transmitting devices"
    }
  ],
  "outdoor": [
    {
      "title": "Trees and Bushes",
      "description": "Watch for wires or strange objects in the foliage. Cameras could be hidden among the branches or leaves",
      "imageName": "tree.fill",
      "content": "Natural outdoor environments provide excellent camouflage for surveillance equipment, with trees and bushes offering both concealment and elevated vantage points. Key areas to inspect include:\\n\\n• **Tree Branches**: Cameras can be mounted on branches, especially those with clear sightlines to windows, doors, or outdoor living spaces. Look for devices that don't match the natural environment.\\n\\n• **Hollow Trees**: Tree cavities and hollows can house larger surveillance systems. Check for any wires running up tree trunks or unusual installations.\\n\\n• **Dense Bushes**: Shrubs near windows or pathways may conceal cameras. Look for lens reflections or non-natural objects within the foliage.\\n\\n• **Fake Branches**: Artificial branches or leaves can be added to real plants to hide cameras. Check for any foliage that looks too perfect or doesn't match the rest of the plant.\\n\\n• **Bird Houses and Feeders**: These common yard decorations can be modified to include cameras. Inspect any that are positioned to view your property rather than attract wildlife.\\n\\n• **Garden Stakes**: Decorative stakes and plant supports can house slim cameras. Be wary of any that seem unnecessarily tall or face toward buildings.\\n\\n**Detection Methods**:\\n- Walk around your property from different angles\\n- Look for wires that don't belong to legitimate lighting or irrigation\\n- Check for disturbed soil or mulch indicating recent installation\\n- Use binoculars to inspect hard-to-reach areas\\n- Notice any pruning that creates unnatural sightlines\\n\\n**Warning Signs**:\\n- Wires running up trees or through bushes\\n- Fresh cuts or damage to bark\\n- Objects that don't weather like natural materials\\n- Unusual bird houses or decorations facing your home"
    },
    {
      "title": "Outdoor Furniture",
      "description": "Look over chairs, tables, and other outdoor pieces carefully. Hidden cameras might be placed in cushions, legs, or beneath surfaces",
      "imageName": "chair.fill",
      "content": "Outdoor furniture provides numerous hiding opportunities for surveillance devices due to its stationary nature and proximity to living spaces. Key areas to inspect include:\\n\\n• **Chair and Table Legs**: Hollow metal or plastic furniture legs can house slim cameras and wiring. Check for any caps or plugs that seem loose or modified.\\n\\n• **Cushions and Pillows**: Weather-resistant outdoor cushions can conceal cameras in seams or zippers. Feel for hard objects or unusual weight distribution.\\n\\n• **Umbrella Poles and Bases**: Patio umbrellas offer height and central positioning. Inspect poles for modifications and check umbrella mechanisms for hidden devices.\\n\\n• **Under-Table Surfaces**: The underside of tables provides concealment with downward viewing angles. Look for any attached devices or unusual modifications.\\n\\n• **Armrests and Joints**: Furniture joints and armrests can hide small cameras. Check for any holes or gaps that don't match the furniture's design.\\n\\n• **Built-in Features**: Tables with fire pits, coolers, or storage compartments offer additional hiding spaces. Inspect all compartments and mechanisms thoroughly.\\n\\n**Inspection Methods**:\\n- Lift cushions and check underneath\\n- Feel along all furniture edges and joints\\n- Look for any non-standard screws or modifications\\n- Check if furniture pieces are unusually heavy\\n- Inspect areas that face seating or gathering spots\\n\\n**Security Tips**:\\n- Be cautious of pre-furnished outdoor spaces\\n- Notice any furniture positioned unusually\\n- Check new furniture additions carefully\\n- Consider the viewing angles from each piece\\n- Store cushions indoors when not in use to prevent tampering"
    },
    {
      "title": "Garden Decorations",
      "description": "Statues, gnomes, and decorative items often have intricate details and varied construction. Observing these features can give insight into their design.",
      "imageName": "leaf.fill",
      "content": "Garden decorations are perfect hiding spots for outdoor surveillance equipment because they're expected to be stationary and blend into landscaping. Common concealment locations include:\\n\\n• **Garden Statues**: Figurines, angels, and ornamental statues can have cameras hidden in eyes, mouths, or hollow sections. Larger statues may house entire surveillance systems.\\n\\n• **Garden Gnomes**: These popular decorations are frequently modified to include cameras. Check for any gnomes positioned to watch entryways or windows rather than gardens.\\n\\n• **Decorative Rocks**: Fake rocks are commercially available as camera housings. Look for rocks that seem too perfect, lightweight, or positioned oddly.\\n\\n• **Water Features**: Fountains, birdbaths, and pond decorations can hide cameras and provide power through pump wiring. Inspect any water features facing your home.\\n\\n• **Solar Lights**: Path lights and decorative solar fixtures can be modified to include cameras powered by their solar panels. Check for any with unusual lenses or positioning.\\n\\n• **Wind Chimes and Spinners**: Hanging decorations can conceal cameras while their movement masks any slight camera adjustments. Look for any that seem heavier than expected.\\n\\n**Inspection Tips**:\\n- Test the weight of decorative items - cameras add weight\\n- Look for decorations that face your home rather than the garden\\n- Check for solar panels on items that don't need power\\n- Inspect any decorations you didn't place yourself\\n- Notice items positioned for viewing rather than aesthetics\\n\\n**Red Flags**:\\n- Decorations with unexpected wires or cables\\n- Items that don't weather naturally over time\\n- Decorations placed in unusual locations\\n- Any garden items that emit heat or have LED lights\\n- Objects that appeared without your knowledge"
    },
    {
      "title": "Garage Doors and Eaves",
      "description": "Pay attention to small openings or reflective surfaces in various areas, as these are common design features in many devices.",
      "imageName": "door.garage.double.bay.closed.trianglebadge.exclamationmark",
      "content": "Building exteriors, particularly garage areas and roof eaves, provide numerous hiding opportunities for surveillance equipment with easy access to power and elevated viewing angles. Critical areas to examine include:\\n\\n• **Garage Door Frames**: The frame and trim around garage doors can conceal slim cameras. Check for any holes or modifications in the weatherstripping or frame.\\n\\n• **Eaves and Soffits**: Roof overhangs provide weather protection for cameras. Look for any new holes, unusual vents, or devices that don't match existing fixtures.\\n\\n• **Downspouts and Gutters**: Rain gutters can hide cameras and wiring. Check for any sections that seem different or have unexpected openings.\\n\\n• **Exterior Light Fixtures**: Porch lights, flood lights, and decorative fixtures near garages can be replaced with camera-equipped versions. Inspect all outdoor lighting carefully.\\n\\n• **Garage Windows**: Small windows or decorative glass in garage doors may have cameras mounted behind them. Look for any additions or modifications to window areas.\\n\\n• **Ventilation Openings**: Garage vents and attic ventilation can hide cameras. Check that all vents are legitimate and properly installed.\\n\\n**What to Look For**:\\n- New or mismatched screws in siding or trim\\n- Holes that don't serve an obvious purpose\\n- Wiring that runs along exterior walls\\n- Light fixtures that seem newer or different\\n- Any modifications to existing structures\\n\\n**Security Considerations**:\\n- Regularly inspect your home's exterior\\n- Document existing fixtures with photos\\n- Notice any work done without your knowledge\\n- Check areas that provide views of driveways and entrances\\n- Consider installing your own security system for comparison"
    },
    {
      "title": "Mailboxes",
      "description": "Observe the inside and exterior of mailboxes for design features or components that may be part of their construction.",
      "imageName": "envelope.fill",
      "content": "Mailboxes and postal areas are strategic locations for surveillance because they provide regular opportunities to monitor coming and going activities. Important areas to inspect include:\\n\\n• **Mailbox Interior**: Cameras can be hidden inside mailboxes to capture anyone approaching. Check for any devices attached to the inner walls or door.\\n\\n• **Mailbox Posts**: Hollow posts or decorative toppers can house cameras with views of driveways and front entrances. Look for any modifications or unusual attachments.\\n\\n• **Decorative Mailbox Surrounds**: Brick or stone structures around mailboxes can conceal larger surveillance systems. Check for any holes or gaps that could hide lenses.\\n\\n• **Newspaper Boxes**: Separate boxes for newspapers or packages may contain cameras. Inspect any boxes that seem unnecessarily large or have unusual features.\\n\\n• **Address Markers**: Decorative numbers or plaques near mailboxes can incorporate hidden cameras. Look for any that seem thicker than necessary or have small openings.\\n\\n• **Package Drop Boxes**: With increased home deliveries, package boxes may be modified to include surveillance. Check for any internal modifications or unusual weight.\\n\\n**Detection Strategies**:\\n- Open and thoroughly inspect mailbox interiors\\n- Check for any wires running to or from the mailbox\\n- Look for solar panels that could power cameras\\n- Test if decorative elements are hollow or solid\\n- Notice any mailbox modifications you didn't authorize\\n\\n**Privacy Concerns**:\\n- Mailboxes provide information about residents and schedules\\n- Cameras here can capture visitors and delivery personnel\\n- Consider the viewing angles from your mailbox location\\n- Be aware of any new installations near postal areas\\n- Report suspicious modifications to postal authorities if needed"
    }
  ]
}
""" 
